version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Build started on `date`
      - echo Building the Docker image...
      - export BUILD_APP_VERSION=$(date +%Y.%m.%d.%H%M%S)
      - echo Build App Version '$BUILD_APP_VERSION'
      - chmod +x gradlew
      - ./gradlew bootBuildImage --imageName $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$BUILD_APP_VERSION
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image..
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$BUILD_APP_VERSION
      - printf '{"ImageURI":"%s"}' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$BUILD_APP_VERSION > imageDetail.json
artifacts:
  files:
    - taskdef.json
    - appspec.yaml
    - imageDetail.json
cache:
  paths:
    - '/root/.gradle/caches/**/*'
    - '.gradle/**/*'
    - '/root/.gradle/wrapper/**/*'
    - 'gradle/**/*'