spring:
  datasource:
    url: jdbc:postgresql://tastezip-postgre-db-dev.cpfqzhwelygz.ap-northeast-2.rds.amazonaws.com:5432/tastezip
    username: tastezip_admin
    password: aktwlq123
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
